baseURL = "/"
languageCode = "en-us"
title = "The OCC Environmental Data Commons"
theme = "kube"
description = "Repository for environmental public data sets of scientific interest, hosted as part of the Open Science Data Cloud Ecosystem"
Paginate = 4
[Params]
  RSSLink = "/index.xml"
  author = "Open Commons Consortium" # add your company name
  github = "https://github.com/occ-data" # add your github profile name
  twitter = "OCC_Data" # add your twitter profile
  email = "info@occ-data.org"


[[menu.main]]
    name = "More Data"
    weight = 3
    url = "https://www.opensciencedatacloud.org/publicdata/?commons_type=Environmental"
[[menu.main]]
    name = "NEXRAD"
    weight = 2
    url = "/nexrad/"
[[menu.main]]
    name = "GOES-16"
    weight = 1
    url = "/goes16/"
